In [16]:
import numpy as np

#### 1D array

In [17]:
a1 = range(0,10)
arr = np.array(a1)
print(arr)
print(type(arr))

for i in arr:
    print(i)

print(arr[1])
print(arr[1:4])
print(arr[:4])


[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
0
1
2
3
4
5
6
7
8
9
1
[1 2 3]
[0 1 2 3]


#### 2D array

In [18]:
a2 = [[1,2],[3,4],[5,6]]
a2d = np.array(a2)
print(a2d)

print(a2d[1][1])
print(a2d[:,1])
print(a2d[:,0:1])

[[1 2]
 [3 4]
 [5 6]]
4
[2 4 6]
[[1]
 [3]
 [5]]


#### find the dimension of array

In [19]:
a2d.shape

(3, 2)

#### reshape array

In [20]:
print(a2d.reshape(2,3))

[[1 2 3]
 [4 5 6]]


#### reassigning and subsetting
#### reassigining some elements in array

In [21]:
a2d[0,0]  = 10
print(a2d)

[[10  2]
 [ 3  4]
 [ 5  6]]


In [24]:
print(a2d[2,0])

5


### creating subarray

In [25]:
sub_a2d = a2d[0:2, 1:2]
sub_a2d

array([[2],
       [4]])

### copying of array

In [27]:
a2d_cpy = a2d.copy()
a2d_cpy

array([[10,  2],
       [ 3,  4],
       [ 5,  6]])

### other ways to create arrays

In [30]:
n1 =  np.ones(10) #creates 1d array with all ones
print("n1=",n1)
n2 = np.ones((3,3)) #create 2d array with all ones
print("n1=",n2)
n3 = np.zeros((2,2)) #create 2d array with all zero
print("n1=",n3)
n4 = np.full((2,2),5) #create 2d array with all fives
print("n1=",n4)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[5 5]
 [5 5]]
