In [1]:
import numpy as np

In [53]:
a1 = range(1,10)
arr = np.array([[1,2,3],[3,4,5],[5,6,10]])
arr[:3]

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [ 5,  6, 10]])

In [55]:
cpy = arr.copy()

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [ 5,  6, 10]])

In [66]:
n1 = np.random.randint(0,10,(2,2))
n1

array([[5, 7],
       [1, 6]])